mkdir web
cd web
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/index.html
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/master.css
mkdir assign 
cd assign
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/assign/assign.css
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/assign/assign.html
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/assign/bruce.jpeg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/assign/hulk.jpg
cd ..
mkdir js
cd js
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/js/jquery-slim.min.js
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/js/popper.min.js
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/js/bootstrap.min.js
cd ..
mkdir css
cd css
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/css/bootstrap.min.css
cd ..

