mkdir Web
cd Web
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/Basics/index.html
mkdir js
cd js
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/js/jquery-slim.min.js
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/js/popper.min.js
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/js/bootstrap.min.js
cd ..
mkdir css
cd css
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/css/bootstrap.min.css
touch master.css
cd ..
mkdir images
cd images
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/Reality.jpg 
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/Thor.jpg  
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/bruce.jpeg 
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/captain-a.jpg 
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/hulk.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/iron-man.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/mind.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/soul.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/power.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/space.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/time.jpg
wget https://raw.githubusercontent.com/GLUG-REVA/Web-Basics/master/images/spider-man.jpg
cd ..
